$ =
	handleStreamError: require '../../helper/handle-stream-error'
	packageJson:       require '../../../../package.json'
	config:            require '../../../../gulp-angular-config.js'
	del:               require 'del'
	changed:           require 'gulp-changed'
	if:                require 'gulp-if'
	less:              require 'gulp-less'
	sass:              require 'gulp-sass'
	util:              require 'gulp-util'
	autoprefixer:      require 'gulp-autoprefixer'
	size:              require 'gulp-size'
	ngClassify:        require 'gulp-ng-classify'
	coffeelint:        require 'gulp-coffeelint'
	coffee:            require 'gulp-coffee'
	wiredep:           require 'wiredep'
	inject:            require 'gulp-inject'
	gracefulChokidar:  require 'graceful-chokidar'
	path:              require 'path'
	browserSync:       require 'browser-sync'
	runSequence:       require 'run-sequence'
	imagemin:          require 'gulp-imagemin'
	mainBowerFiles:    require 'main-bower-files'
	filter:            require 'gulp-filter'
	merge:             require 'gulp-merge'
	minifyHtml:        require 'gulp-minify-html'
	ngHtml2js:         require 'gulp-ng-html2js'
	rename:            require 'gulp-rename'
	lazypipe:          require 'lazypipe'
	copy:              require 'gulp-copy'
	cssretarget:       require 'gulp-cssretarget'
	useref:            require 'gulp-useref'
	minifyCss:         require 'gulp-minify-css'
	ngAnnotate:        require 'gulp-ng-annotate'
	uglify:            require 'gulp-uglify'
	uglifySaveLicense: require 'uglify-save-license'
	rev:               require 'gulp-rev'
	revReplace:        require 'gulp-rev-replace'
	fs:                require 'fs'

module.exports = (gulp) ->
	require(task)(gulp, $) for task in [
		'./clean'
		'./transpile'
		'./inject'
		'./watch'
		'./serve'
		'./dist'
	]
